### ISSUE TITLE
Players unable to apply damage

### ISSUE THREAD

**Issue by tinwe** [fvtt-fria-ligan/twilight2000-foundry-vtt#132]
### Describe the bug

My players aren't able to apply damage themselves. It says they lack permissions.
Is this by design, so that only the Referee can apply the damage, or what settings should I enable for them to be able to apply the damage themselves?
I really don't want to give all players ownership to the NPC characters nor their tokens, for this.

### Reproduction

Have a player fire a weapon, target an enemy token, and try to apply the resulting damage from the attack.

### System Info

```sh
Several different player clients, mostly Chrome, but using the latest Foundry and T2k system.
Foundry 10, build 291
T2k4: 10.2.0
```

### Logs

We only excperience these errors while during our sessions, but when I tried to recreate it on my own using their login, I don't get the same error message, but I do experience these logs when trying to apply the damage.

t2k4e.js:15 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'length')
[Detected 1 package: system:t2k4e]
    at ActorT2K.applyDamageToCharacter (t2k4e.js:15:16219)
    at ActorT2K.applyDamage (t2k4e.js:15:15719)
    at _applyDamage (t2k4e.js:15:29588)
    at Object.callback (t2k4e.js:15:28139)
    at #onClickItem (foundry.js:56177:11)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
applyDamageToCharacter @ t2k4e.js:15
applyDamage @ t2k4e.js:15
_applyDamage @ t2k4e.js:15
callback @ t2k4e.js:15
#onClickItem @ foundry.js:56177
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by uhu79** [comment]
it seems that "apply damage" does not work anymore at all, neither for players nor for GM

**Comment by stories-with-dice** [comment]
Any update on this?
